### ISSUE TITLE
removal option

### ISSUE THREAD

**Issue by digitalkaoz** [Prashanth-Nelli/treewalker#2]
Hey there,

great tiny library. love it!

do you think it is possible to make it possible to remove nodes on `resolveTree`?

maybe with a `return` from the callback which is used in the treewalker to either remove a complete subtree.

what do you think? is it possible?

**Comment by Prashanth-Nelli** [comment]
Hi digitalkaoz
yes it is possible i added an example in the documentation so please go through it

**Comment by Prashanth-Nelli** [comment]
HI digitalkaoz
please use the latest version of treewalker module

**Comment by digitalkaoz** [comment]
yeah ok, looks good so far, but what i thought was removal of `obj` from its parent from within the callback.

**Comment by Prashanth-Nelli** [comment]
Hi,I am not able to understand that scenario could please provide any example
